steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME',
      '--build-arg', 'PUBLIC_MY_NAME=Abe Flansburg',
      '--build-arg', 'PUBLIC_MY_EMAIL=me@engabe.com',
      '--build-arg', 'PUBLIC_MY_LINKED_IN_URL=https://www.linkedin.com/in/abramflansburg/',
      '.'
    ]

images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME' 